services:
  backend:
    image: backend:latest
    build: ./backend
    environment:
      PATH_TO_MODEL: /models/model.cbm
    volumes:
      - ./backend/models:/models
  frontend:
    image: frontend:latest
    build: ./frontend
    environment:
      BACKEND_URL: http://backend:5000
    ports:
      - 3000:3000
